# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/animaux/detail_animaux_folder/detail_animaux_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(439, 525)
        self.label_titre_detail_animaux_2 = QtWidgets.QLabel(Dialog)
        self.label_titre_detail_animaux_2.setGeometry(QtCore.QRect(10, 150, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_titre_detail_animaux_2.setFont(font)
        self.label_titre_detail_animaux_2.setObjectName("label_titre_detail_animaux_2")
        self.label_sans_enclos_erreure_details_animaux = QtWidgets.QLabel(Dialog)
        self.label_sans_enclos_erreure_details_animaux.setGeometry(QtCore.QRect(20, 480, 411, 41))
        self.label_sans_enclos_erreure_details_animaux.setObjectName("label_sans_enclos_erreure_details_animaux")
        self.label_classe_information_detail_animaux = QtWidgets.QLabel(Dialog)
        self.label_classe_information_detail_animaux.setGeometry(QtCore.QRect(10, 120, 181, 16))
        self.label_classe_information_detail_animaux.setObjectName("label_classe_information_detail_animaux")
        self.listView_ls_animal_detail_animaux = QtWidgets.QListView(Dialog)
        self.listView_ls_animal_detail_animaux.setGeometry(QtCore.QRect(10, 180, 411, 291))
        self.listView_ls_animal_detail_animaux.setObjectName("listView_ls_animal_detail_animaux")
        self.label_titre_detail_animaux = QtWidgets.QLabel(Dialog)
        self.label_titre_detail_animaux.setGeometry(QtCore.QRect(10, -20, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_titre_detail_animaux.setFont(font)
        self.label_titre_detail_animaux.setObjectName("label_titre_detail_animaux")
        self.label_id_detail_animaux = QtWidgets.QLabel(Dialog)
        self.label_id_detail_animaux.setGeometry(QtCore.QRect(10, 50, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_id_detail_animaux.setFont(font)
        self.label_id_detail_animaux.setObjectName("label_id_detail_animaux")
        self.label_id_information_detail_animaux = QtWidgets.QLabel(Dialog)
        self.label_id_information_detail_animaux.setGeometry(QtCore.QRect(10, 70, 181, 16))
        self.label_id_information_detail_animaux.setObjectName("label_id_information_detail_animaux")
        self.label_classe_detail_animaux = QtWidgets.QLabel(Dialog)
        self.label_classe_detail_animaux.setGeometry(QtCore.QRect(10, 100, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_classe_detail_animaux.setFont(font)
        self.label_classe_detail_animaux.setObjectName("label_classe_detail_animaux")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_titre_detail_animaux_2.setText(_translate("Dialog", "Attribut de l\'animal:"))
        self.label_sans_enclos_erreure_details_animaux.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">*Cette animale n'as actuelement pas d'enclos</span></p><p><br/></p></body></html>"))
        self.label_classe_information_detail_animaux.setText(_translate("Dialog", "NONE"))
        self.label_titre_detail_animaux.setText(_translate("Dialog", "Détail:"))
        self.label_id_detail_animaux.setText(_translate("Dialog", "id de l\'animal:"))
        self.label_id_information_detail_animaux.setText(_translate("Dialog", "NONE"))
        self.label_classe_detail_animaux.setText(_translate("Dialog", "Classe:"))
