# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/succes_pop_up_interface_folder.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(358, 146)
        self.label_succes_serialisation_pop_up = QtWidgets.QLabel(Dialog)
        self.label_succes_serialisation_pop_up.setGeometry(QtCore.QRect(60, 30, 241, 16))
        self.label_succes_serialisation_pop_up.setObjectName("label_succes_serialisation_pop_up")
        self.label_erreure_serialisation_pop_up = QtWidgets.QLabel(Dialog)
        self.label_erreure_serialisation_pop_up.setGeometry(QtCore.QRect(0, 60, 411, 41))
        self.label_erreure_serialisation_pop_up.setObjectName("label_erreure_serialisation_pop_up")
        self.pushButton_ok_serialisation_enclo = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok_serialisation_enclo.setGeometry(QtCore.QRect(130, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ok_serialisation_enclo.setFont(font)
        self.pushButton_ok_serialisation_enclo.setObjectName("pushButton_ok_serialisation_enclo")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_succes_serialisation_pop_up.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Sérialisation effectué avec succès!</span></p></body></html>"))
        self.label_erreure_serialisation_pop_up.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt; color:#ff0000;\">*Une erreure est survenue lors de la sérialisation</span></p><p><span style=\" font-size:12pt;\"><br/></span></p></body></html>"))
        self.pushButton_ok_serialisation_enclo.setText(_translate("Dialog", "Ok"))
