# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/animaux/create1_enclos_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(536, 404)
        self.pushButton_suivant_crea1_animaux = QtWidgets.QPushButton(Dialog)
        self.pushButton_suivant_crea1_animaux.setGeometry(QtCore.QRect(10, 320, 241, 51))
        self.pushButton_suivant_crea1_animaux.setObjectName("pushButton_suivant_crea1_animaux")
        self.label_existant_erreure_id_crea1_animaux = QtWidgets.QLabel(Dialog)
        self.label_existant_erreure_id_crea1_animaux.setGeometry(QtCore.QRect(10, 140, 411, 16))
        self.label_existant_erreure_id_crea1_animaux.setObjectName("label_existant_erreure_id_crea1_animaux")
        self.pushButton_annulez_crea1_animaux = QtWidgets.QPushButton(Dialog)
        self.pushButton_annulez_crea1_animaux.setGeometry(QtCore.QRect(270, 320, 241, 51))
        self.pushButton_annulez_crea1_animaux.setObjectName("pushButton_annulez_crea1_animaux")
        self.lineEdit_id_crea1_animaux = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_id_crea1_animaux.setGeometry(QtCore.QRect(10, 50, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_id_crea1_animaux.setFont(font)
        self.lineEdit_id_crea1_animaux.setText("")
        self.lineEdit_id_crea1_animaux.setObjectName("lineEdit_id_crea1_animaux")
        self.comboBox_classe_crea1_animaux = QtWidgets.QComboBox(Dialog)
        self.comboBox_classe_crea1_animaux.setGeometry(QtCore.QRect(10, 240, 231, 41))
        self.comboBox_classe_crea1_animaux.setObjectName("comboBox_classe_crea1_animaux")
        self.label_format_erreure_id_crea1_enclos = QtWidgets.QLabel(Dialog)
        self.label_format_erreure_id_crea1_enclos.setGeometry(QtCore.QRect(10, 90, 411, 41))
        self.label_format_erreure_id_crea1_enclos.setObjectName("label_format_erreure_id_crea1_enclos")
        self.label_id_crea1_animaux = QtWidgets.QLabel(Dialog)
        self.label_id_crea1_animaux.setGeometry(QtCore.QRect(10, 20, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_id_crea1_animaux.setFont(font)
        self.label_id_crea1_animaux.setObjectName("label_id_crea1_animaux")
        self.label_classe_crea1_animaux = QtWidgets.QLabel(Dialog)
        self.label_classe_crea1_animaux.setGeometry(QtCore.QRect(10, 200, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_classe_crea1_animaux.setFont(font)
        self.label_classe_crea1_animaux.setObjectName("label_classe_crea1_animaux")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_suivant_crea1_animaux.setText(_translate("Dialog", "Suivant"))
        self.label_existant_erreure_id_crea1_animaux.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">*L\'id existe déjà</span></p><p><br/></p></body></html>"))
        self.pushButton_annulez_crea1_animaux.setText(_translate("Dialog", "Annulez"))
        self.label_format_erreure_id_crea1_enclos.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">*L\'id doit commencer par &lt;&lt; A &gt;&gt; et être suivit de 5 chiffres</span></p><p><span style=\" color:#ff0000;\">Ex: A12345</span></p><p><br/></p></body></html>"))
        self.label_id_crea1_animaux.setText(_translate("Dialog", "id de l\'animal:"))
        self.label_classe_crea1_animaux.setText(_translate("Dialog", "Classe animal:"))
