# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/enclos/detail_enclos_folder/detail_enclos_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 623)
        self.listView_ls_animal_detail_enclos = QtWidgets.QListView(Dialog)
        self.listView_ls_animal_detail_enclos.setGeometry(QtCore.QRect(40, 240, 411, 291))
        self.listView_ls_animal_detail_enclos.setObjectName("listView_ls_animal_detail_enclos")
        self.label_titre_detail_enclos = QtWidgets.QLabel(Dialog)
        self.label_titre_detail_enclos.setGeometry(QtCore.QRect(40, -10, 331, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_titre_detail_enclos.setFont(font)
        self.label_titre_detail_enclos.setObjectName("label_titre_detail_enclos")
        self.label_id_detail_enclo = QtWidgets.QLabel(Dialog)
        self.label_id_detail_enclo.setGeometry(QtCore.QRect(40, 60, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_id_detail_enclo.setFont(font)
        self.label_id_detail_enclo.setObjectName("label_id_detail_enclo")
        self.label_id_information_detail_enclo = QtWidgets.QLabel(Dialog)
        self.label_id_information_detail_enclo.setGeometry(QtCore.QRect(40, 80, 181, 16))
        self.label_id_information_detail_enclo.setObjectName("label_id_information_detail_enclo")
        self.label_ecosysteme_detail_enclo = QtWidgets.QLabel(Dialog)
        self.label_ecosysteme_detail_enclo.setGeometry(QtCore.QRect(40, 110, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_ecosysteme_detail_enclo.setFont(font)
        self.label_ecosysteme_detail_enclo.setObjectName("label_ecosysteme_detail_enclo")
        self.label_ecostysteme_information_detail_enclo = QtWidgets.QLabel(Dialog)
        self.label_ecostysteme_information_detail_enclo.setGeometry(QtCore.QRect(40, 130, 181, 16))
        self.label_ecostysteme_information_detail_enclo.setObjectName("label_ecostysteme_information_detail_enclo")
        self.label_nettoyage_detail_enclo = QtWidgets.QLabel(Dialog)
        self.label_nettoyage_detail_enclo.setGeometry(QtCore.QRect(40, 160, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_nettoyage_detail_enclo.setFont(font)
        self.label_nettoyage_detail_enclo.setObjectName("label_nettoyage_detail_enclo")
        self.label_nettoyage_information_detail_enclo = QtWidgets.QLabel(Dialog)
        self.label_nettoyage_information_detail_enclo.setGeometry(QtCore.QRect(40, 180, 181, 16))
        self.label_nettoyage_information_detail_enclo.setObjectName("label_nettoyage_information_detail_enclo")
        self.label_ls_animaux_detail_enclo = QtWidgets.QLabel(Dialog)
        self.label_ls_animaux_detail_enclo.setGeometry(QtCore.QRect(40, 210, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_ls_animaux_detail_enclo.setFont(font)
        self.label_ls_animaux_detail_enclo.setObjectName("label_ls_animaux_detail_enclo")

        self.label_selection_erreure_details_enclos = QtWidgets.QLabel(Dialog)
        self.label_selection_erreure_details_enclos.setGeometry(QtCore.QRect(50, 540, 411, 41))
        self.label_selection_erreure_details_enclos.setObjectName("label_selection_erreure_details_enclos")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_titre_detail_enclos.setText(_translate("Dialog", "Détail:"))
        self.label_id_detail_enclo.setText(_translate("Dialog", "id de l\'enclo:"))
        self.label_id_information_detail_enclo.setText(_translate("Dialog", "NONE"))
        self.label_ecosysteme_detail_enclo.setText(_translate("Dialog", "Catégorie écosysteme:"))
        self.label_ecostysteme_information_detail_enclo.setText(_translate("Dialog", "NONE"))
        self.label_nettoyage_detail_enclo.setText(_translate("Dialog", "Dernier nettoyage:"))
        self.label_nettoyage_information_detail_enclo.setText(_translate("Dialog", "NONE"))
        self.label_ls_animaux_detail_enclo.setText(_translate("Dialog", "List animaux:"))


        self.label_selection_erreure_details_enclos.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">*Un animal doit être sélectioner au préalable</span></p><p><br/></p></body></html>"))
