# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/enclos/list_selection_animaux_enclos_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(423, 652)
        self.lineEdit_recherche_id_gestion_enclos = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_recherche_id_gestion_enclos.setGeometry(QtCore.QRect(10, 110, 151, 31))
        self.lineEdit_recherche_id_gestion_enclos.setObjectName("lineEdit_recherche_id_gestion_enclos")
        self.label_recherche_list_animaux_enclos = QtWidgets.QLabel(Dialog)
        self.label_recherche_list_animaux_enclos.setGeometry(QtCore.QRect(10, 10, 371, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_recherche_list_animaux_enclos.setFont(font)
        self.label_recherche_list_animaux_enclos.setObjectName("label_recherche_list_animaux_enclos")
        self.label_recherche_ecosysteme_list_animaux_enclos = QtWidgets.QLabel(Dialog)
        self.label_recherche_ecosysteme_list_animaux_enclos.setGeometry(QtCore.QRect(10, 200, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_recherche_ecosysteme_list_animaux_enclos.setFont(font)
        self.label_recherche_ecosysteme_list_animaux_enclos.setObjectName("label_recherche_ecosysteme_list_animaux_enclos")
        self.comboBox_recherche_ecosysteme_list_animaux_enclos = QtWidgets.QComboBox(Dialog)
        self.comboBox_recherche_ecosysteme_list_animaux_enclos.setGeometry(QtCore.QRect(10, 230, 181, 31))
        self.comboBox_recherche_ecosysteme_list_animaux_enclos.setObjectName("comboBox_recherche_ecosysteme_list_animaux_enclos")
        self.listView_recherche_list_animaux_enclos = QtWidgets.QListView(Dialog)
        self.listView_recherche_list_animaux_enclos.setGeometry(QtCore.QRect(10, 280, 401, 291))
        self.listView_recherche_list_animaux_enclos.setObjectName("listView_recherche_list_animaux_enclos")
        self.label_format_erreure_id_recherche_list_animaux_enclos = QtWidgets.QLabel(Dialog)
        self.label_format_erreure_id_recherche_list_animaux_enclos.setGeometry(QtCore.QRect(10, 150, 411, 41))
        self.label_format_erreure_id_recherche_list_animaux_enclos.setObjectName("label_format_erreure_id_recherche_list_animaux_enclos")
        self.label_id_crea_list_animaux_enclos = QtWidgets.QLabel(Dialog)
        self.label_id_crea_list_animaux_enclos.setGeometry(QtCore.QRect(10, 90, 191, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_id_crea_list_animaux_enclos.setFont(font)
        self.label_id_crea_list_animaux_enclos.setObjectName("label_id_crea_list_animaux_enclos")
        self.pushButton_ajouter_list_animaux_enclos = QtWidgets.QPushButton(Dialog)
        self.pushButton_ajouter_list_animaux_enclos.setGeometry(QtCore.QRect(10, 590, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ajouter_list_animaux_enclos.setFont(font)
        self.pushButton_ajouter_list_animaux_enclos.setObjectName("pushButton_ajouter_list_animaux_enclos")
        self.pushButton_ajouter_list_animaux_enclos_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_ajouter_list_animaux_enclos_2.setGeometry(QtCore.QRect(250, 590, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_ajouter_list_animaux_enclos_2.setFont(font)
        self.pushButton_ajouter_list_animaux_enclos_2.setObjectName("pushButton_ajouter_list_animaux_enclos_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_recherche_list_animaux_enclos.setText(_translate("Dialog", "Recherche et Gestion Animaux"))
        self.label_recherche_ecosysteme_list_animaux_enclos.setText(_translate("Dialog", "Classe :"))
        self.label_format_erreure_id_recherche_list_animaux_enclos.setText(_translate("Dialog", "<html><head/><body><p><span style=\" color:#ff0000;\">*L\'id doit commencer par &lt;&lt; A &gt;&gt; et être suivit de 5 chiffres</span></p><p><span style=\" color:#ff0000;\">Ex: A12345</span></p><p><br/></p></body></html>"))
        self.label_id_crea_list_animaux_enclos.setText(_translate("Dialog", "id de l\'animal:"))
        self.pushButton_ajouter_list_animaux_enclos.setText(_translate("Dialog", "Ajouter"))
        self.pushButton_ajouter_list_animaux_enclos_2.setText(_translate("Dialog", "Détail"))
