# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface/fenetre_principale_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(822, 567)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_titre_zoo = QtWidgets.QLabel(self.centralwidget)
        self.label_titre_zoo.setGeometry(QtCore.QRect(320, 20, 241, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_titre_zoo.setFont(font)
        self.label_titre_zoo.setObjectName("label_titre_zoo")
        self.pushButton_animaux = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_animaux.setGeometry(QtCore.QRect(280, 180, 241, 51))
        self.pushButton_animaux.setObjectName("pushButton_animaux")
        self.pushButton_enclos = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_enclos.setGeometry(QtCore.QRect(280, 240, 241, 51))
        self.pushButton_enclos.setObjectName("pushButton_enclos")
        self.pushButton_quitter = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_quitter.setGeometry(QtCore.QRect(280, 300, 241, 51))
        self.pushButton_quitter.setObjectName("pushButton_quitter")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_titre_zoo.setText(_translate("MainWindow", "Gestion Zoo"))
        self.pushButton_animaux.setText(_translate("MainWindow", "Animaux"))
        self.pushButton_enclos.setText(_translate("MainWindow", "Enclos"))
        self.pushButton_quitter.setText(_translate("MainWindow", "Quitter"))
